name: Docs
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.3"
      - run: uv pip install mkdocs-material "mkdocstrings[python]" mike
      - run: uv run mkdocs gh-deploy --force